lib: [
  "_build/install/default/lib/teamproject/META"
  "_build/install/default/lib/teamproject/dune-package"
  "_build/install/default/lib/teamproject/teamproject.a"
  "_build/install/default/lib/teamproject/teamproject.cma"
  "_build/install/default/lib/teamproject/teamproject.cmi"
  "_build/install/default/lib/teamproject/teamproject.cmt"
  "_build/install/default/lib/teamproject/teamproject.cmx"
  "_build/install/default/lib/teamproject/teamproject.cmxa"
  "_build/install/default/lib/teamproject/teamproject.ml"
]
libexec: [
  "_build/install/default/lib/teamproject/teamproject.cmxs"
]
bin: [
  "_build/install/default/bin/teamproject"
]
doc: [
  "_build/install/default/doc/teamproject/README.md"
]
